import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import path from 'node:path';
import {config,root} from './config.js';
import {pool} from './database/db.js';
import authRoutes from './auth.js';
import routes from './routes.js';
import {ok,wrap} from './utils.js';
export const app=express();
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:{directives:{'img-src':["'self'",'data:','https://*.tile.openstreetmap.org'],'connect-src':["'self'"],'script-src':["'self'"],'style-src':["'self'","'unsafe-inline'"]}}}));
app.use(cors({origin:config.origin}));app.use(express.json({limit:'16kb'}));
app.use('/api',rateLimit({windowMs:60000,limit:240,standardHeaders:'draft-7',legacyHeaders:false,message:{success:false,message:'Too many requests; wait a minute'}}));
app.get('/api/health',wrap(async(req,res)=>{await pool.query('SELECT 1');ok(res,{status:'ready',demo:config.demo});}));
app.use('/api/auth',authRoutes);app.use('/api',routes);
app.use('/api',(req,res)=>res.status(404).json({success:false,message:'API route not found'}));
app.use(express.static(path.join(root,'client/dist')));app.get('*',(req,res)=>res.sendFile(path.join(root,'client/dist/index.html')));
app.use((err,req,res,next)=>{const status=err.status|| (err.code==='23505'?409:err.type==='entity.parse.failed'?400:503);res.status(status).json({success:false,message:err.code==='23505'?'This email is already registered':err.status?err.message:status===400?'Invalid JSON request':'Service unavailable. Check PostgreSQL and try again.'});});
