import {Router} from 'express';
import {pool,transaction} from './database/db.js';
import {auth,demo,organizer} from './auth.js';
import {ok,wrap,fail,integer} from './utils.js';
import * as game from './services/game.js';
import {generateClue} from './services/clues.js';
const r=Router();r.use(auth);
r.get('/hunts',wrap(async(req,res)=>ok(res,(await pool.query('SELECT h.*,(SELECT count(*)::int FROM hunt_participants p JOIN users u ON u.id=p.user_id WHERE p.hunt_id=h.id AND NOT u.simulated) AS players FROM hunts h WHERE active=true')).rows)));
r.get('/hunts/:id',wrap(async(req,res)=>{const h=(await pool.query('SELECT * FROM hunts WHERE id=$1',[integer(req.params.id)])).rows[0];if(!h)throw fail(404,'Hunt not found');ok(res,h);}));
r.post('/hunts/:id/join',wrap(async(req,res)=>{const name=(req.body.teamName||req.user.name)?.trim();if(!name||name.length>60)throw fail(400,'Team name must contain 1–60 characters');const h=(await pool.query('SELECT id FROM hunts WHERE id=$1 AND active=true',[integer(req.params.id)])).rows[0];if(!h)throw fail(404,'Hunt not found');await pool.query('INSERT INTO hunt_participants(hunt_id,user_id,team_name) VALUES($1,$2,$3) ON CONFLICT(hunt_id,user_id) DO NOTHING',[h.id,req.user.id,name]);ok(res,await game.progress(req.user.id,h.id));}));
r.get('/hunts/:id/progress',wrap(async(req,res)=>ok(res,await game.progress(req.user.id,req.params.id))));
r.get('/hunts/:id/leaderboard',wrap(async(req,res)=>ok(res,await game.leaderboard(req.params.id))));
r.get('/hunts/:id/players',wrap(async(req,res)=>{await game.participant(pool,req.user.id,req.params.id);ok(res,(await pool.query('SELECT p.user_id,p.team_name,l.latitude,l.longitude,l.mode,l.updated_at FROM player_locations l JOIN hunt_participants p ON p.id=l.participant_id WHERE p.hunt_id=$1 AND l.updated_at > now()-interval \'5 minutes\'',[integer(req.params.id)])).rows);}));
r.patch('/players/location',wrap(async(req,res)=>ok(res,await game.location(req.user.id,integer(req.body.huntId),req.body))));
for(const [route,complete] of [['check-location',false],['complete-checkpoint',true]])r.post('/hunts/:id/'+route,wrap(async(req,res)=>ok(res,await game.check(req.user.id,req.params.id,req.body.checkpointId,complete))));
r.post('/hunts/:id/hint',wrap(async(req,res)=>ok(res,await game.hint(req.user.id,req.params.id,req.body.checkpointId))));
r.post('/demo/arrival',demo,wrap(async(req,res)=>ok(res,await transaction(async db=>{const p=await game.participant(db,req.user.id,req.body.huntId,true),c=await game.target(db,p);if(!c)throw fail(409,'Hunt finished');await game.saveLocation(db,p,{latitude:c.latitude,longitude:c.longitude,mode:'demo'});return {latitude:c.latitude,longitude:c.longitude,name:c.name};}))));
r.get('/demo/checkpoints/:id',demo,wrap(async(req,res)=>ok(res,(await pool.query('SELECT id,name,latitude,longitude,sequence_number FROM checkpoints WHERE hunt_id=$1 ORDER BY sequence_number',[integer(req.params.id)])).rows)));
r.post('/demo/reset',demo,wrap(async(req,res)=>{await transaction(async db=>{const p=await game.participant(db,req.user.id,req.body.huntId,true);await db.query('DELETE FROM checkpoint_completions WHERE participant_id=$1',[p.id]);await db.query('DELETE FROM hints_used WHERE participant_id=$1',[p.id]);await db.query('DELETE FROM player_locations WHERE participant_id=$1',[p.id]);await db.query('UPDATE hunt_participants SET score=0,current_checkpoint=1,started_at=now(),completed_at=NULL WHERE id=$1',[p.id]);});ok(res,{reset:true});}));
r.post('/demo/simulate',demo,organizer,wrap(async(req,res)=>{const users=(await pool.query('SELECT id FROM users WHERE simulated=true ORDER BY id')).rows;for(const u of users){const p=await game.progress(u.id,1);if(p.clue){const c=(await pool.query('SELECT * FROM checkpoints WHERE id=$1',[p.clue.id])).rows[0];await game.location(u.id,1,{latitude:c.latitude,longitude:c.longitude,mode:'demo'});await game.check(u.id,1,c.id,true);break;}}ok(res,{simulated:true});}));
r.post('/ai/generate-clue',organizer,wrap(async(req,res)=>{const c=(await pool.query('SELECT * FROM checkpoints WHERE name=$1',[req.body.location])).rows[0];if(!c)throw fail(400,'Choose one of the six seeded destinations');ok(res,await generateClue(c));}));
export default r;
